import type { Metadata } from "next";
import { Geologica } from "next/font/google";
import "./globals.scss";

const geologica = Geologica({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geologica.className}>{children}</body>
    </html>
  );
}
